"""places_and_place_reminders

Revision ID: b94b8fa86dae
Revises: 0004_pending_actions_ttl
Create Date: 2026-01-29 14:16:37.604131

"""

from alembic import op
import sqlalchemy as sa



revision = 'b94b8fa86dae'
down_revision = '0004_pending_actions_ttl'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_last_locations',
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('place_reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=8), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('place_id', 'text', 'event', name='uq_place_reminders_place_text_event')
    )
    op.create_index(op.f('ix_place_reminders_active'), 'place_reminders', ['active'], unique=False)
    op.create_index(op.f('ix_place_reminders_event'), 'place_reminders', ['event'], unique=False)
    op.create_index(op.f('ix_place_reminders_place_id'), 'place_reminders', ['place_id'], unique=False)
    op.create_table('places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('radius_m', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'title', name='uq_places_device_title')
    )
    op.create_index(op.f('ix_places_device_id'), 'places', ['device_id'], unique=False)
    op.create_index(op.f('ix_places_title'), 'places', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_places_title'), table_name='places')
    op.drop_index(op.f('ix_places_device_id'), table_name='places')
    op.drop_table('places')
    op.drop_index(op.f('ix_place_reminders_place_id'), table_name='place_reminders')
    op.drop_index(op.f('ix_place_reminders_event'), table_name='place_reminders')
    op.drop_index(op.f('ix_place_reminders_active'), table_name='place_reminders')
    op.drop_table('place_reminders')
    op.drop_table('device_last_locations')
    # ### end Alembic commands ###
